version: 1
source:
  dsn: PROD
# target:
#   driver: ODBC Driver 18 for SQL Server
#   server: DESKTOP-F1E0DKV\SQL2022
#   database: master
#   trusted: "yes"
#   encrypt: "no"
dump:
  tables:
    - sqlci.sqlci.Table_Example:
    - sqlci.sqlci.Table_Example2:
  views:
    - sqlci.sqlci.View_Example:
  procedures:
    - sqlci.sqlci.Procedure_Example:
